select * from customer_shopping_behavior limit 10

--Q.1) What is the total revenue generated by male v/s female customers?
SELECT Gender, SUM(`Purchase Amount (USD)`) as revenue
FROM customer_shopping_behavior
GROUP BY Gender;

--Q.2)Which customers used a discount but still spent more than the average purchase amount?
select `Customer ID`,`Purchase Amount (USD)`
from customer_shopping_behavior
where `Discount Applied`='Yes' and `Purchase Amount (USD)` >= (select avg(`Purchase Amount (USD)`) from customer_shopping_behavior)

--Q.3) Which are the top 5 products with the hihest average review rating?
select `Item Purchased`,ROUND(avg(`Review Rating`),2) as `Average Product Rating`
from customer_shopping_behavior
group by `Item Purchased`
order by avg(`Review Rating`) desc
limit 5;

--Q.4) Compare the average purchase amounts between standard and express shipping.
select `Shipping Type`,round(avg(`Purchase Amount (USD)`),2)
from customer_shopping_behavior
where `Shipping type` in ('Standard','Express')
group by `Shipping Type`

--Q.5) Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-subscribers.
select `Subscription Status`,
COUNT(`Customer ID`) as `total_customers`,
round(avg(`Purchase Amount (USD)`),2) as `avg_spend`,
round(sum(`Purchase Amount (USD)`),2) as `total_revenue`
from customer_shopping_behavior
group by `Subscription Status`
order by `total_revenue`,`avg_spend` desc;

--Q.6) Which 5 products have the highest percentages of purchases with discounts applied?
select `Item Purchased`,
round(100 * sum(case when `Discount Applied`='Yes' then 1 else 0 end)/count(*),2) as `discount_rate`
from customer_shopping_behavior
group by `Item Purchased`
order by `discount_rate` desc
limit 5;

!!--Q.7) Segment customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment.
with `customer_type` as (
select `Customer ID`,`Previous Purchases`,
case
    when `Previous Purchases`=1 then 'New'
    when `Previous Purchases` between 2 and 10 then 'Returning'
    else 'Loyal'
    end as `customer_segment`
from customer_shopping_behavior
)

select  `customer_segment`, count(*) as `Number_of_Customers`  
from `customer_type`
group by `customer_segment`;

!!--Q.8) What are the top 3 most purchased products within each category?
with `item_counts` as(
select `Category`, `Item Purchased`, count(`Customer ID`) as `total_orders`,
row_number() over (partition by `Category` order by count(`Customer ID`) desc) as `item_rank`
from customer_shopping_behavior
group by `Category`,`Item Purchased`
)

select `item_rank`,`Category`,`item Purchased`,`total_orders`
from `item_counts`
where `item_rank`<=3;

!!--Q.9) Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select `Subscription Status`,
count(`Customer ID`) as `repeat_buyers`
from customer_shopping_behavior
where `Previous Purchases` > 5
group by `Subscription Status`


--Q.10) What is the revenue contribution of each age group?
select `Age`,
sum(`Purchase Amount (USD)`) as `total_revenue`
from customer_shopping_behavior
group by `Age`
order by `total_revenue` desc;